# Generated by Django 4.2.10 on 2024-02-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("healthScore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthrecord",
            name="doctorID",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="hospitalID",
            field=models.IntegerField(),
        ),
    ]
