# Generated by Django 4.2 on 2024-03-06 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("healthScore", "0002_alter_healthrecord_doctorid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="userName",
            new_name="username",
        ),
    ]
