# Generated by Django 4.2 on 2024-03-08 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthScore", "0006_remove_user_date_joined"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 8, 13, 51, 13, 776202, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
