# Generated by Django 4.2 on 2024-03-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("healthScore", "0005_alter_user_email_alter_user_name"),
        ("healthScore", "0008_remove_user_date_joined"),
    ]

    operations = []
