# Generated by Django 4.2 on 2024-03-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthScore", "0009_merge_20240309_1423"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
    ]
