# Generated by Django 4.2 on 2024-03-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthScore", "0012_alter_user_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hospital",
            name="email",
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="password",
        ),
        migrations.RemoveField(
            model_name="hospital",
            name="website",
        ),
        migrations.RemoveField(
            model_name="hospitalstaff",
            name="email",
        ),
        migrations.RemoveField(
            model_name="hospitalstaff",
            name="password",
        ),
        migrations.AddField(
            model_name="user",
            name="is_patient",
            field=models.BooleanField(default=False),
        ),
    ]
