# Generated by Django 4.2 on 2024-03-16 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("healthScore", "0012_alter_user_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
