# Generated by Django 4.2 on 2024-03-16 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("healthScore", "0013_remove_hospital_email_remove_hospital_password_and_more"),
        ("healthScore", "0013_remove_user_username"),
    ]

    operations = []
