# Generated by Django 4.2 on 2024-03-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthScore", "0014_merge_20240316_1850"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
    ]
