# Generated by Django 4.2 on 2024-03-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthScore", "0015_alter_user_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_healthcare_worker",
            field=models.BooleanField(default=False),
        ),
    ]
