# Generated by Django 4.2 on 2024-03-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthScore", "0016_user_is_healthcare_worker"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospitalstaff",
            name="userID",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
