# Generated by Django 4.2 on 2024-03-22 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("healthScore", "0013_post"),
        ("healthScore", "0017_hospitalstaff_userid"),
    ]

    operations = []
