# Generated by Django 4.2 on 2024-03-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthScore", "0019_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dummy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test", models.TextField()),
            ],
        ),
    ]
