# Generated by Django 4.2 on 2024-03-27 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("healthScore", "0020_healthhistoryrequest"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HealthHistoryRequest",
            new_name="HealthHistoryAccessRequest",
        ),
    ]
