# Generated by Django 4.2 on 2024-03-30 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("healthScore", "0020_post_updatedat"),
        ("healthScore", "0021_rename_healthhistoryrequest_healthhistoryaccessrequest"),
    ]

    operations = []
