# Generated by Django 4.2 on 2024-04-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthScore", "0022_merge_20240330_1033"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthrecord",
            name="rejectedReason",
            field=models.TextField(default="N/A"),
        ),
    ]
