# Generated by Django 4.2 on 2024-04-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthScore", "0023_healthrecord_rejectedreason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthrecord",
            name="rejectedReason",
            field=models.TextField(null=True),
        ),
    ]
