# Generated by Django 4.2 on 2024-04-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthScore", "0024_alter_healthrecord_rejectedreason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profilePic",
            field=models.TextField(
                default="https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
                null=True,
            ),
        ),
    ]
