# Generated by Django 4.2 on 2024-02-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hospitals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='')),
                ('address', models.TextField(default='')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('contactInfo', models.IntegerField(default='', max_length=10)),
                ('website', models.TextField(default='')),
                ('status', models.TextField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='rejected')),
            ],
        ),
    ]
