# Generated by Django 4.2 on 2024-02-20 21:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthScore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appointmentName', models.TextField()),
                ('appointmentProperties', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.TextField()),
                ('password', models.TextField()),
                ('userName', models.TextField(unique=True)),
                ('dob', models.DateField()),
                ('contactInfo', models.TextField(default='', max_length=10)),
                ('proofOfIdentity', models.TextField(null=True)),
                ('address', models.TextField()),
                ('securityQues', models.TextField(default='')),
                ('securityAns', models.TextField(default='')),
                ('gender', models.TextField(default='')),
                ('profilePic', models.TextField(null=True)),
                ('bloodGroup', models.TextField()),
                ('requests', models.JSONField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='contactInfo',
            field=models.TextField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='hospitalStaff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin', models.BooleanField(default=False, null=True)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('specialization', models.TextField(default='')),
                ('contactInfo', models.TextField(default='', max_length=10)),
                ('securityQues', models.TextField(default='')),
                ('securityAns', models.TextField(default='')),
                ('hospitalID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthScore.hospitals')),
            ],
        ),
        migrations.CreateModel(
            name='healthRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doctorID', models.TextField(default='')),
                ('hospitalID', models.TextField(default='')),
                ('status', models.TextField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='rejected')),
                ('dateTime', models.DateTimeField(default=datetime.date(2024, 2, 20))),
                ('healthDocuments', models.JSONField(null=True)),
                ('appointmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthScore.appointment')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthScore.user')),
            ],
        ),
        migrations.CreateModel(
            name='communityInteraction',
            fields=[
                ('userName', models.TextField()),
                ('postID', models.AutoField(primary_key=True, serialize=False)),
                ('postTitle', models.TextField(default='')),
                ('postDescription', models.TextField(default='')),
                ('postTimeStamp', models.DateTimeField(default=datetime.date(2024, 2, 20))),
                ('upvote', models.IntegerField(default=0)),
                ('downvote', models.IntegerField(default=0)),
                ('tags', models.TextField(default='', null=True)),
                ('postComments', models.JSONField(null=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthScore.user')),
            ],
        ),
    ]
