# Generated by Django 4.2 on 2024-02-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthScore", "0002_appointment_communityinteraction_healthrecord_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="userName",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
