# Generated by Django 4.2 on 2024-02-20 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthScore', '0003_hospital_rename_appointmentname_appointment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityinteraction',
            name='postTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 23, 28, 33, 282250)),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 23, 28, 33, 281549)),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 20, 23, 28, 33, 281572)),
        ),
    ]
